### ISSUE TITLE
The new version 2.0.0 is not in npm

### ISSUE THREAD

**Issue by ameba6** [origin1tech/connect-sequelize#6]
The new version 2.0.0 is not in NPM, what is still there is 1.0.8, How can you or I upload the new realise to NPM?

I encourage you to continue, good job

Thanks.

**Comment by origin1tech** [comment]
Published it, thx for the heads up. Unless there's anything else can I close this?

**Comment by ameba6** [comment]
Yes. Thank you very much.

**Comment by origin1tech** [comment]
published to npm.
