### ISSUE TITLE
SequelizeStore.destroy crash with sequelize 2.1+

### ISSUE THREAD

**Issue by shawnbissell** [origin1tech/connect-sequelize#7]
When destroying a session I get the following error. I believe it's related to the use the the old success and error methods which are now missing in sequelize 2.1 and above.

Sat, 01 Aug 2015 21:02:33 GMT session:connect-sequelize DESTROYING wbWtprgYijmwtKDjuPkW1m_zm8gi-pAM
Executing (default): DELETE FROM "ExpressSession" WHERE "sid" IN (SELECT "sid" FROM "ExpressSession" WHERE "sid" = 'wbWtprgYijmwtKDjuPkW1m_zm8gi-pAM' LIMIT 1)
Unhandled rejection TypeError: undefined is not a function
    at findSession (/Users/shawn/WebstormProjects/web/node_modules/connect-sequelize/lib/connect-sequelize.js:109:24)
    at processImmediate [as _immediateCallback] (timers.js:367:17)
From previous event:
    at Promise.then (/Users/shawn/WebstormProjects/web/node_modules/sequelize/lib/promise.js:21:17)
    at SequelizeStore.destroySession [as destroy] (/Users/shawn/WebstormProjects/web/node_modules/connect-sequelize/lib/connect-sequelize.js:101:49)

**Comment by origin1tech** [comment]
It probably is. I won’t have time to look at it for a little bit pull-requests welcome. 

It should be a very simple fix. My apologies for the delay only so much time in day :)

Regards,

Carey Hazelton
chazelton@origin1.com <mailto:chazelton@origin1.com>
Confidentiality Notice: The information contained in this electronic transmission, is privileged and confidential and is intended only for the recipient(s) named above. If the reader of this message is not the recipient(s) named above, or an authorized agent of such recipient(s) responsible for delivering it to the intended recipient(s), you are hereby notified that you have received this electronic transmission in error. Any review, dissemination, distribution, or copying of this electronic transmission including any attachments is strictly prohibited. If you have received this electronic transmission in error, please notify the sender immediately. Origin1 Technologies.

**Comment by shawnbissell** [comment]
Yes it was easy
https://github.com/origin1tech/connect-sequelize/pull/8

**Comment by origin1tech** [comment]
I figured it would be.

**Comment by origin1tech** [comment]
I'll leave this open for a bit, let me know if u run into any issues over the next few before we close it.

**Comment by jarrodconnolly** [comment]
I was also running into this issue, so far the fix looks good to me.

**Comment by origin1tech** [comment]
Good deal I'll close for now.
