### ISSUE TITLE
Last update was not pushed to NPM

### ISSUE THREAD

**Issue by jpgdev** [origin1tech/connect-sequelize#9]
The last update to fix the problem with Sequelize 2.1 does not seem to be pushed on NPM, since I have a similar error when calling the `store.destroy` as #7.

`Unhandled rejection TypeError: session.destroy(...).success is not a function`

**Comment by jarrodconnolly** [comment]
+1
Please publish the version with the #7 fix to NPM.

**Comment by origin1tech** [comment]
Done! sorry thought I had already done this.

**Comment by shawnbissell** [comment]
Doesn't seem to have worked. The code in connect-sequelize@2.0.1 does not match latest in github. Also the package.json is still at version 2.0.0.

**Comment by origin1tech** [comment]
hmm strange. maybe there’s something strange going on with NPM just updated. I’ll dig into it later this evening.

sorry for the delay. I’ll sort it out by end of day tomorrow. fyi.

**Comment by origin1tech** [comment]
This should be fixed. if someone could verify please...

**Comment by jpgdev** [comment]
It works fine now, thanks.

**Comment by shawnbissell** [comment]
+1 works now. Thanks!
